# Sweeping an input value

A parameter sweep changes a constant the flow reads with `param()`; an input sweep changes a record's own
value. `overrides` without `at` writes an input column before anything runs; overriding a value a step
produces needs `at=<step path>`.

**How an experiment runs.** The runner feeds the *baseline* (the unchanged flow) and every *scenario* the
same records, one batch at a time. Each **metric** gets its own copy per scenario and collects through hooks:
a *global* metric reads the flow's output; a *step* metric (`nodes="<glob>"`) reads what matching steps
wrote, on the records that ran them. `summarise()` gives a typed summary; a **plot** draws one metric's
summaries across scenarios. `result.show()` lays it all out.

In [1]:
from decider.experiments import *
from example_projects.experiments.loan_pipeline import applications, build

ENTRY = "example_projects.experiments.loan_pipeline:build"
pipeline = build()   # ratio -> rate -> pricing (secured | unsecured) -> approved, payment
loans = applications(200_000)
loans.head()

shape: (5, 3)
┌────────┬────────┬────────────┐
│ income ┆ debt   ┆ collateral │
│ ---    ┆ ---    ┆ ---        │
│ f64    ┆ f64    ┆ f64        │
╞════════╪════════╪════════════╡
│ 3829.0 ┆ 718.0  ┆ 1344.0     │
│ 3454.0 ┆ 938.0  ┆ 3913.0     │
│ 4704.0 ┆ 1956.0 ┆ 0.0        │
│ 3797.0 ┆ 1960.0 ┆ 16821.0    │
│ 2939.0 ┆ 387.0  ┆ 0.0        │
└────────┴────────┴────────────┘

In [2]:
exp = (Experiment("collateral", pipeline, loans, entry=ENTRY)
       .scenario("all_secured", overrides={"collateral": 5_000.0})
       .scenario("none_secured", overrides={"collateral": 0.0})
       .scenario("cheap_base_rate", at="loans/rate", overrides={"rate": 0.05})
       .metric(Divergence(column="approved"),
               Histogram(name="rate", column="rate", nodes="loans/pricing", range=(0.0, 0.3)),
               BranchFlows(outcome="approved"))
       .plot(Changes(metric="divergence"), Distribution(metric="rate"),
             Sankey(name="flows_none_secured", metric="branch_flows", scenario="none_secured")))
result = exp.run()
result.plots["rate"].show()

Figure(grammar='vega-lite', spec={'config': {'view': {'continuousWidth': 300, 'continuousHeight': 300}}, 'data': {'values': [{'scenario': 'baseline', 'start': 0.0, 'end': 0.015, 'records': 0}, {'scenario': 'baseline', 'start': 0.015, 'end': 0.03, 'records': 0}, {'scenario': 'baseline', 'start': 0.03, 'end': 0.045, 'records': 0}, {'scenario': 'baseline', 'start': 0.045, 'end': 0.06, 'records': 0}, {'scenario': 'baseline', 'start': 0.06, 'end': 0.075, 'records': 0}, {'scenario': 'baseline', 'start': 0.075, 'end': 0.09, 'records': 41194}, {'scenario': 'baseline', 'start': 0.09, 'end': 0.105, 'records': 65643}, {'scenario': 'baseline', 'start': 0.105, 'end': 0.12, 'records': 12960}, {'scenario': 'baseline', 'start': 0.12, 'end': 0.135, 'records': 206}, {'scenario': 'baseline', 'start': 0.135, 'end': 0.15, 'records': 10838}, {'scenario': 'baseline', 'start': 0.15, 'end': 0.16499999999999998, 'records': 31447}, {'scenario': 'baseline', 'start': 0.16499999999999998, 'end': 0.18, 'records': 24088}, {'scenario': 'baseline', 'start': 0.18, 'end': 0.195, 'records': 10658}, {'scenario': 'baseline', 'start': 0.195, 'end': 0.21, 'records': 2739}, {'scenario': 'baseline', 'start': 0.21, 'end': 0.22499999999999998, 'records': 227}, {'scenario': 'baseline', 'start': 0.22499999999999998, 'end': 0.24, 'records': 0}, {'scenario': 'baseline', 'start': 0.24, 'end': 0.255, 'records': 0}, {'scenario': 'baseline', 'start': 0.255, 'end': 0.27, 'records': 0}, {'scenario': 'baseline', 'start': 0.27, 'end': 0.285, 'records': 0}, {'scenario': 'baseline', 'start': 0.285, 'end': 0.3, 'records': 0}, {'scenario': 'all_secured', 'start': 0.0, 'end': 0.015, 'records': 0}, {'scenario': 'all_secured', 'start': 0.015, 'end': 0.03, 'records': 0}, {'scenario': 'all_secured', 'start': 0.03, 'end': 0.045, 'records': 0}, {'scenario': 'all_secured', 'start': 0.045, 'end': 0.06, 'records': 0}, {'scenario': 'all_secured', 'start': 0.06, 'end': 0.075, 'records': 0}, {'scenario': 'all_secured', 'start': 0.075, 'end': 0.09, 'records': 68697}, {'scenario': 'all_secured', 'start': 0.09, 'end': 0.105, 'records': 109400}, {'scenario': 'all_secured', 'start': 0.105, 'end': 0.12, 'records': 21549}, {'scenario': 'all_secured', 'start': 0.12, 'end': 0.135, 'records': 354}, {'scenario': 'all_secured', 'start': 0.135, 'end': 0.15, 'records': 0}, {'scenario': 'all_secured', 'start': 0.15, 'end': 0.16499999999999998, 'records': 0}, {'scenario': 'all_secured', 'start': 0.16499999999999998, 'end': 0.18, 'records': 0}, {'scenario': 'all_secured', 'start': 0.18, 'end': 0.195, 'records': 0}, {'scenario': 'all_secured', 'start': 0.195, 'end': 0.21, 'records': 0}, {'scenario': 'all_secured', 'start': 0.21, 'end': 0.22499999999999998, 'records': 0}, {'scenario': 'all_secured', 'start': 0.22499999999999998, 'end': 0.24, 'records': 0}, {'scenario': 'all_secured', 'start': 0.24, 'end': 0.255, 'records': 0}, {'scenario': 'all_secured', 'start': 0.255, 'end': 0.27, 'records': 0}, {'scenario': 'all_secured', 'start': 0.27, 'end': 0.285, 'records': 0}, {'scenario': 'all_secured', 'start': 0.285, 'end': 0.3, 'records': 0}, {'scenario': 'none_secured', 'start': 0.0, 'end': 0.015, 'records': 0}, {'scenario': 'none_secured', 'start': 0.015, 'end': 0.03, 'records': 0}, {'scenario': 'none_secured', 'start': 0.03, 'end': 0.045, 'records': 0}, {'scenario': 'none_secured', 'start': 0.045, 'end': 0.06, 'records': 0}, {'scenario': 'none_secured', 'start': 0.06, 'end': 0.075, 'records': 0}, {'scenario': 'none_secured', 'start': 0.075, 'end': 0.09, 'records': 0}, {'scenario': 'none_secured', 'start': 0.09, 'end': 0.105, 'records': 0}, {'scenario': 'none_secured', 'start': 0.105, 'end': 0.12, 'records': 0}, {'scenario': 'none_secured', 'start': 0.12, 'end': 0.135, 'records': 0}, {'scenario': 'none_secured', 'start': 0.135, 'end': 0.15, 'records': 27269}, {'scenario': 'none_secured', 'start': 0.15, 'end': 0.16499999999999998, 'records': 78375}, {'scenario': 'none_secured', 'start': 0.16499999999999998, 'end': 0.18, 'records': 60131}, {'scenario': 'none_secured', 'start': 0.18, 'end': 0.195, 'records': 26799}, {'scenario': 'none_secured', 'start': 0.195, 'end': 0.21, 'records': 6847}, {'scenario': 'none_secured', 'start': 0.21, 'end': 0.22499999999999998, 'records': 579}, {'scenario': 'none_secured', 'start': 0.22499999999999998, 'end': 0.24, 'records': 0}, {'scenario': 'none_secured', 'start': 0.24, 'end': 0.255, 'records': 0}, {'scenario': 'none_secured', 'start': 0.255, 'end': 0.27, 'records': 0}, {'scenario': 'none_secured', 'start': 0.27, 'end': 0.285, 'records': 0}, {'scenario': 'none_secured', 'start': 0.285, 'end': 0.3, 'records': 0}, {'scenario': 'cheap_base_rate', 'start': 0.0, 'end': 0.015, 'records': 0}, {'scenario': 'cheap_base_rate', 'start': 0.015, 'end': 0.03, 'records': 0}, {'scenario': 'cheap_base_rate', 'start': 0.03, 'end': 0.045, 'records': 120003}, {'scenario': 'cheap_base_rate', 'start': 0.045, 'end': 0.06, 'records': 0}, {'scenario': 'cheap_base_rate', 'start': 0.06, 'end': 0.075, 'records': 0}, {'scenario': 'cheap_base_rate', 'start': 0.075, 'end': 0.09, 'records': 0}, {'scenario': 'cheap_base_rate', 'start': 0.09, 'end': 0.105, 'records': 57937}, {'scenario': 'cheap_base_rate', 'start': 0.105, 'end': 0.12, 'records': 21666}, {'scenario': 'cheap_base_rate', 'start': 0.12, 'end': 0.135, 'records': 394}, {'scenario': 'cheap_base_rate', 'start': 0.135, 'end': 0.15, 'records': 0}, {'scenario': 'cheap_base_rate', 'start': 0.15, 'end': 0.16499999999999998, 'records': 0}, {'scenario': 'cheap_base_rate', 'start': 0.16499999999999998, 'end': 0.18, 'records': 0}, {'scenario': 'cheap_base_rate', 'start': 0.18, 'end': 0.195, 'records': 0}, {'scenario': 'cheap_base_rate', 'start': 0.195, 'end': 0.21, 'records': 0}, {'scenario': 'cheap_base_rate', 'start': 0.21, 'end': 0.22499999999999998, 'records': 0}, {'scenario': 'cheap_base_rate', 'start': 0.22499999999999998, 'end': 0.24, 'records': 0}, {'scenario': 'cheap_base_rate', 'start': 0.24, 'end': 0.255, 'records': 0}, {'scenario': 'cheap_base_rate', 'start': 0.255, 'end': 0.27, 'records': 0}, {'scenario': 'cheap_base_rate', 'start': 0.27, 'end': 0.285, 'records': 0}, {'scenario': 'cheap_base_rate', 'start': 0.285, 'end': 0.3, 'records': 0}]}, 'mark': {'type': 'bar'}, 'encoding': {'color': {'field': 'scenario', 'type': 'nominal'}, 'opacity': {'condition': {'param': 'param_366548e304bb77de', 'value': 0.55}, 'value': 0.05}, 'tooltip': [{'field': 'scenario', 'type': 'nominal'}, {'field': 'start', 'format': '.4g', 'type': 'quantitative'}, {'field': 'end', 'format': '.4g', 'type': 'quantitative'}, {'field': 'records', 'type': 'quantitative'}], 'x': {'bin': 'binned', 'field': 'start', 'title': 'rate', 'type': 'quantitative'}, 'x2': {'field': 'end'}, 'y': {'field': 'records', 'stack': None, 'type': 'quantitative'}}, 'params': [{'name': 'param_366548e304bb77de', 'select': {'type': 'point', 'fields': ['scenario']}, 'bind': 'legend'}], 'title': 'rate by scenario', '$schema': 'https://vega.github.io/schema/vega-lite/v6.4.1.json'})

`validate` returns every problem with a definition at once, before anything runs.

In [3]:
broken = (Experiment("broken", pipeline, loans)
          .scenario("no_point", overrides={"rate": 0.1})
          .metric(ValueCounts(column="approved"))
          .plot(Changes(metric="value_counts")))
validate(broken.def_, pipeline)

["no_point: override 'rate' is produced, not an input; declare 'at: <step path>'",
 "plot 'value_counts' needs a Divergences summary; metric 'value_counts' gives Counts"]

In [4]:
result.show()

### collateral: completed

200,000 records · revision `b7091562ef82` · 3 scenario(s) next to the baseline

shape: (4, 6)
┌─────────────────┬───────────┬─────────┬──────────┬─────────────────────────────────┬───────┐
│ scenario        ┆ status    ┆ records ┆ revision ┆ changes                         ┆ error │
│ ---             ┆ ---       ┆ ---     ┆ ---      ┆ ---                             ┆ ---   │
│ str             ┆ str       ┆ i64     ┆ null     ┆ str                             ┆ null  │
╞═════════════════╪═══════════╪═════════╪══════════╪═════════════════════════════════╪═══════╡
│ baseline        ┆ completed ┆ 200000  ┆ null     ┆ unchanged                       ┆ null  │
│ all_secured     ┆ completed ┆ 200000  ┆ null     ┆ set {"collateral": 5000.0}      ┆ null  │
│ none_secured    ┆ completed ┆ 200000  ┆ null     ┆ set {"collateral": 0.0}         ┆ null  │
│ cheap_base_rate ┆ completed ┆ 200000  ┆ null     ┆ set {"rate": 0.05} after loans… ┆ null  │
└─────────────────┴───────────┴─────────┴──────────┴─────────────────────────────────┴───────┘

#### divergence

`divergence` of `approved` in the flow's output

shape: (4, 6)
┌─────────────────┬──────────┬──────────┬─────────┬───────┬─────────┐
│ scenario        ┆ column   ┆ compared ┆ changed ┆ first ┆ samples │
│ ---             ┆ ---      ┆ ---      ┆ ---     ┆ ---   ┆ ---     │
│ str             ┆ str      ┆ i64      ┆ i64     ┆ null  ┆ str     │
╞═════════════════╪══════════╪══════════╪═════════╪═══════╪═════════╡
│ baseline        ┆ approved ┆ 200000   ┆ 0       ┆ null  ┆ []      │
│ all_secured     ┆ approved ┆ 200000   ┆ 0       ┆ null  ┆ []      │
│ none_secured    ┆ approved ┆ 200000   ┆ 0       ┆ null  ┆ []      │
│ cheap_base_rate ┆ approved ┆ 200000   ┆ 0       ┆ null  ┆ []      │
└─────────────────┴──────────┴──────────┴─────────┴───────┴─────────┘

Figure(grammar='vega-lite', spec={'config': {'view': {'continuousWidth': 300, 'continuousHeight': 300}}, 'data': {'values': [{'scenario': 'baseline', 'changed': 0, 'compared': 200000, 'first': None}, {'scenario': 'all_secured', 'changed': 0, 'compared': 200000, 'first': None}, {'scenario': 'none_secured', 'changed': 0, 'compared': 200000, 'first': None}, {'scenario': 'cheap_base_rate', 'changed': 0, 'compared': 200000, 'first': None}]}, 'mark': {'type': 'bar'}, 'encoding': {'tooltip': [{'field': 'scenario', 'type': 'nominal'}, {'field': 'changed', 'type': 'quantitative'}, {'field': 'compared', 'type': 'quantitative'}, {'field': 'first', 'title': 'first changed record', 'type': 'quantitative'}], 'x': {'field': 'scenario', 'sort': None, 'type': 'nominal'}, 'y': {'field': 'changed', 'title': 'records changed', 'type': 'quantitative'}}, 'title': 'approved changed vs baseline', '$schema': 'https://vega.github.io/schema/vega-lite/v6.4.1.json'})

#### rate

`histogram` of `rate` at steps matching `loans/pricing`

shape: (4, 7)
┌─────────────────┬────────┬──────────────────┬────────────────────────────┬───────┬───────┬───────┐
│ scenario        ┆ column ┆ edges            ┆ counts                     ┆ below ┆ above ┆ nulls │
│ ---             ┆ ---    ┆ ---              ┆ ---                        ┆ ---   ┆ ---   ┆ ---   │
│ str             ┆ str    ┆ str              ┆ str                        ┆ i64   ┆ i64   ┆ i64   │
╞═════════════════╪════════╪══════════════════╪════════════════════════════╪═══════╪═══════╪═══════╡
│ baseline        ┆ rate   ┆ [0, 0.015, 0.03, ┆ [0, 0, 0, 0, 0, 41194, …]  ┆ 0     ┆ 0     ┆ 0     │
│                 ┆        ┆ 0.045, 0.06, …   ┆ (20)                       ┆       ┆       ┆       │
│ all_secured     ┆ rate   ┆ [0, 0.015, 0.03, ┆ [0, 0, 0, 0, 0, 68697, …]  ┆ 0     ┆ 0     ┆ 0     │
│                 ┆        ┆ 0.045, 0.06, …   ┆ (20)                       ┆       ┆       ┆       │
│ none_secured    ┆ rate   ┆ [0, 0.015, 0.03, ┆ [0, 0, 0, 0, 0, 0, …] (20) ┆ 0     ┆ 0     ┆ 0     │
│                 ┆        ┆ 0.045, 0.06, …   ┆                            ┆       ┆       ┆       │
│ cheap_base_rate ┆ rate   ┆ [0, 0.015, 0.03, ┆ [0, 0, 120003, 0, 0, 0, …] ┆ 0     ┆ 0     ┆ 0     │
│                 ┆        ┆ 0.045, 0.06, …   ┆ (20…                       ┆       ┆       ┆       │
└─────────────────┴────────┴──────────────────┴────────────────────────────┴───────┴───────┴───────┘

Figure(grammar='vega-lite', spec={'config': {'view': {'continuousWidth': 300, 'continuousHeight': 300}}, 'data': {'values': [{'scenario': 'baseline', 'start': 0.0, 'end': 0.015, 'records': 0}, {'scenario': 'baseline', 'start': 0.015, 'end': 0.03, 'records': 0}, {'scenario': 'baseline', 'start': 0.03, 'end': 0.045, 'records': 0}, {'scenario': 'baseline', 'start': 0.045, 'end': 0.06, 'records': 0}, {'scenario': 'baseline', 'start': 0.06, 'end': 0.075, 'records': 0}, {'scenario': 'baseline', 'start': 0.075, 'end': 0.09, 'records': 41194}, {'scenario': 'baseline', 'start': 0.09, 'end': 0.105, 'records': 65643}, {'scenario': 'baseline', 'start': 0.105, 'end': 0.12, 'records': 12960}, {'scenario': 'baseline', 'start': 0.12, 'end': 0.135, 'records': 206}, {'scenario': 'baseline', 'start': 0.135, 'end': 0.15, 'records': 10838}, {'scenario': 'baseline', 'start': 0.15, 'end': 0.16499999999999998, 'records': 31447}, {'scenario': 'baseline', 'start': 0.16499999999999998, 'end': 0.18, 'records': 24088}, {'scenario': 'baseline', 'start': 0.18, 'end': 0.195, 'records': 10658}, {'scenario': 'baseline', 'start': 0.195, 'end': 0.21, 'records': 2739}, {'scenario': 'baseline', 'start': 0.21, 'end': 0.22499999999999998, 'records': 227}, {'scenario': 'baseline', 'start': 0.22499999999999998, 'end': 0.24, 'records': 0}, {'scenario': 'baseline', 'start': 0.24, 'end': 0.255, 'records': 0}, {'scenario': 'baseline', 'start': 0.255, 'end': 0.27, 'records': 0}, {'scenario': 'baseline', 'start': 0.27, 'end': 0.285, 'records': 0}, {'scenario': 'baseline', 'start': 0.285, 'end': 0.3, 'records': 0}, {'scenario': 'all_secured', 'start': 0.0, 'end': 0.015, 'records': 0}, {'scenario': 'all_secured', 'start': 0.015, 'end': 0.03, 'records': 0}, {'scenario': 'all_secured', 'start': 0.03, 'end': 0.045, 'records': 0}, {'scenario': 'all_secured', 'start': 0.045, 'end': 0.06, 'records': 0}, {'scenario': 'all_secured', 'start': 0.06, 'end': 0.075, 'records': 0}, {'scenario': 'all_secured', 'start': 0.075, 'end': 0.09, 'records': 68697}, {'scenario': 'all_secured', 'start': 0.09, 'end': 0.105, 'records': 109400}, {'scenario': 'all_secured', 'start': 0.105, 'end': 0.12, 'records': 21549}, {'scenario': 'all_secured', 'start': 0.12, 'end': 0.135, 'records': 354}, {'scenario': 'all_secured', 'start': 0.135, 'end': 0.15, 'records': 0}, {'scenario': 'all_secured', 'start': 0.15, 'end': 0.16499999999999998, 'records': 0}, {'scenario': 'all_secured', 'start': 0.16499999999999998, 'end': 0.18, 'records': 0}, {'scenario': 'all_secured', 'start': 0.18, 'end': 0.195, 'records': 0}, {'scenario': 'all_secured', 'start': 0.195, 'end': 0.21, 'records': 0}, {'scenario': 'all_secured', 'start': 0.21, 'end': 0.22499999999999998, 'records': 0}, {'scenario': 'all_secured', 'start': 0.22499999999999998, 'end': 0.24, 'records': 0}, {'scenario': 'all_secured', 'start': 0.24, 'end': 0.255, 'records': 0}, {'scenario': 'all_secured', 'start': 0.255, 'end': 0.27, 'records': 0}, {'scenario': 'all_secured', 'start': 0.27, 'end': 0.285, 'records': 0}, {'scenario': 'all_secured', 'start': 0.285, 'end': 0.3, 'records': 0}, {'scenario': 'none_secured', 'start': 0.0, 'end': 0.015, 'records': 0}, {'scenario': 'none_secured', 'start': 0.015, 'end': 0.03, 'records': 0}, {'scenario': 'none_secured', 'start': 0.03, 'end': 0.045, 'records': 0}, {'scenario': 'none_secured', 'start': 0.045, 'end': 0.06, 'records': 0}, {'scenario': 'none_secured', 'start': 0.06, 'end': 0.075, 'records': 0}, {'scenario': 'none_secured', 'start': 0.075, 'end': 0.09, 'records': 0}, {'scenario': 'none_secured', 'start': 0.09, 'end': 0.105, 'records': 0}, {'scenario': 'none_secured', 'start': 0.105, 'end': 0.12, 'records': 0}, {'scenario': 'none_secured', 'start': 0.12, 'end': 0.135, 'records': 0}, {'scenario': 'none_secured', 'start': 0.135, 'end': 0.15, 'records': 27269}, {'scenario': 'none_secured', 'start': 0.15, 'end': 0.16499999999999998, 'records': 78375}, {'scenario': 'none_secured', 'start': 0.16499999999999998, 'end': 0.18, 'records': 60131}, {'scenario': 'none_secured', 'start': 0.18, 'end': 0.195, 'records': 26799}, {'scenario': 'none_secured', 'start': 0.195, 'end': 0.21, 'records': 6847}, {'scenario': 'none_secured', 'start': 0.21, 'end': 0.22499999999999998, 'records': 579}, {'scenario': 'none_secured', 'start': 0.22499999999999998, 'end': 0.24, 'records': 0}, {'scenario': 'none_secured', 'start': 0.24, 'end': 0.255, 'records': 0}, {'scenario': 'none_secured', 'start': 0.255, 'end': 0.27, 'records': 0}, {'scenario': 'none_secured', 'start': 0.27, 'end': 0.285, 'records': 0}, {'scenario': 'none_secured', 'start': 0.285, 'end': 0.3, 'records': 0}, {'scenario': 'cheap_base_rate', 'start': 0.0, 'end': 0.015, 'records': 0}, {'scenario': 'cheap_base_rate', 'start': 0.015, 'end': 0.03, 'records': 0}, {'scenario': 'cheap_base_rate', 'start': 0.03, 'end': 0.045, 'records': 120003}, {'scenario': 'cheap_base_rate', 'start': 0.045, 'end': 0.06, 'records': 0}, {'scenario': 'cheap_base_rate', 'start': 0.06, 'end': 0.075, 'records': 0}, {'scenario': 'cheap_base_rate', 'start': 0.075, 'end': 0.09, 'records': 0}, {'scenario': 'cheap_base_rate', 'start': 0.09, 'end': 0.105, 'records': 57937}, {'scenario': 'cheap_base_rate', 'start': 0.105, 'end': 0.12, 'records': 21666}, {'scenario': 'cheap_base_rate', 'start': 0.12, 'end': 0.135, 'records': 394}, {'scenario': 'cheap_base_rate', 'start': 0.135, 'end': 0.15, 'records': 0}, {'scenario': 'cheap_base_rate', 'start': 0.15, 'end': 0.16499999999999998, 'records': 0}, {'scenario': 'cheap_base_rate', 'start': 0.16499999999999998, 'end': 0.18, 'records': 0}, {'scenario': 'cheap_base_rate', 'start': 0.18, 'end': 0.195, 'records': 0}, {'scenario': 'cheap_base_rate', 'start': 0.195, 'end': 0.21, 'records': 0}, {'scenario': 'cheap_base_rate', 'start': 0.21, 'end': 0.22499999999999998, 'records': 0}, {'scenario': 'cheap_base_rate', 'start': 0.22499999999999998, 'end': 0.24, 'records': 0}, {'scenario': 'cheap_base_rate', 'start': 0.24, 'end': 0.255, 'records': 0}, {'scenario': 'cheap_base_rate', 'start': 0.255, 'end': 0.27, 'records': 0}, {'scenario': 'cheap_base_rate', 'start': 0.27, 'end': 0.285, 'records': 0}, {'scenario': 'cheap_base_rate', 'start': 0.285, 'end': 0.3, 'records': 0}]}, 'mark': {'type': 'bar'}, 'encoding': {'color': {'field': 'scenario', 'type': 'nominal'}, 'opacity': {'condition': {'param': 'param_366548e304bb77de', 'value': 0.55}, 'value': 0.05}, 'tooltip': [{'field': 'scenario', 'type': 'nominal'}, {'field': 'start', 'format': '.4g', 'type': 'quantitative'}, {'field': 'end', 'format': '.4g', 'type': 'quantitative'}, {'field': 'records', 'type': 'quantitative'}], 'x': {'bin': 'binned', 'field': 'start', 'title': 'rate', 'type': 'quantitative'}, 'x2': {'field': 'end'}, 'y': {'field': 'records', 'stack': None, 'type': 'quantitative'}}, 'params': [{'name': 'param_366548e304bb77de', 'select': {'type': 'point', 'fields': ['scenario']}, 'bind': 'legend'}], 'title': 'rate by scenario', '$schema': 'https://vega.github.io/schema/vega-lite/v6.4.1.json'})

#### branch_flows

`branch_flows` of `approved` at steps matching `*`

shape: (4, 4)
┌─────────────────┬──────────┬─────────────────────────────────┬─────────────────────────────────┐
│ scenario        ┆ outcome  ┆ nodes                           ┆ links                           │
│ ---             ┆ ---      ┆ ---                             ┆ ---                             │
│ str             ┆ str      ┆ str                             ┆ str                             │
╞═════════════════╪══════════╪═════════════════════════════════╪═════════════════════════════════╡
│ baseline        ┆ approved ┆ [{"id": "in", "label": "200000… ┆ [{"source": "in", "target": "l… │
│ all_secured     ┆ approved ┆ [{"id": "in", "label": "200000… ┆ [{"source": "in", "target": "l… │
│ none_secured    ┆ approved ┆ [{"id": "in", "label": "200000… ┆ [{"source": "in", "target": "l… │
│ cheap_base_rate ┆ approved ┆ [{"id": "in", "label": "200000… ┆ [{"source": "in", "target": "l… │
└─────────────────┴──────────┴─────────────────────────────────┴─────────────────────────────────┘

<Vega chart: Record flow through branch arms into an outcome. Adapted from David Bacci's Sankey chart (https://github.com/PBI-David/Deneb-Showcase, MIT License, Copyright (c) 2023 Davide Bacci); see sankey.vg.LICENSE.>